// <auto-generated />
using CustomizeAuthAppJWT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomizeAuthAppJWT.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507145655_AddPermissions")]
    partial class AddPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CustomizeAuthAppJWT.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ReadReports"
                        },
                        new
                        {
                            Id = 2,
                            Name = "WriteReports"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ManageUsers"
                        });
                });

            modelBuilder.Entity("CustomizeAuthAppJWT.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionName = "ReadReports",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            PermissionName = "WriteReports",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            PermissionName = "ManageUsers",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 4,
                            PermissionName = "ReadReports",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("CustomizeAuthAppJWT.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
